name = "jd-matcher"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "jd-matcher-db"
database_id = "951ab241-9803-4de7-88be-233f21ea14be"

[[kv_namespaces]]
binding = "SESSION_KV"
id = "eafd099fdff8492f9dabb4beb3887415"

[[vectorize]]
binding = "JOB_DESC_EMBEDDINGS"
index_name = "job-desc-embeddings"

[[vectorize]]
binding = "RESUME_EMBEDDINGS"
index_name = "resume-embeddings"

[[queues.producers]]
queue = "jd-jobs-pool"
binding = "JOBS_QUEUE"

[[queues.consumers]]
queue = "jd-jobs-pool"
max_batch_size = 1
max_retries = 3

[triggers]
crons = ["0 */2 * * *", "*/10 * * * *", "0 */3 * * *"]

[vars]
LLM_OPENROUTER_BASEURL = "https://api.gptsapi.net/v1"
LLM_OPENROUTER_MODEL = "gpt-4o-mini"
LLM_OPENROUTER_EMBEDDINGMODEL = "text-embedding-ada-002"
LLM_DEEPSEEK_BASEURL = "https://api.deepseek.com/v1"
LLM_DEEPSEEK_MODEL = "deepseek-chat"
LLM_DEEPSEEK_REASONINGEFFORT = "high"

[observability.logs]
enabled = true
invocation_logs = true
