
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "pgsql:jdmatcher:1qaz!QAZ@tcp(127.0.0.1:5432)/jdmatcherdb"
        descriptionTag: true
