// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"jd-matcher/internal/dao/internal"
)

// internalUserMatchedJobDao is internal type for wrapping internal DAO implements.
type internalUserMatchedJobDao = *internal.UserMatchedJobDao

// userMatchedJobDao is the data access object for table user_matched_job.
// You can define custom methods on it to extend its functionality as you wish.
type userMatchedJobDao struct {
	internalUserMatchedJobDao
}

var (
	// UserMatchedJob is globally public accessible object for table user_matched_job operations.
	UserMatchedJob = userMatchedJobDao{
		internal.NewUserMatchedJobDao(),
	}
)

// Fill with you ideas below.
